#!/usr/bin/env python3

target_padding_size = 1024

prefix = '<!-- '
suffix = ' -->\n'
padding = '*' * (target_padding_size - (len(prefix) + len(suffix)))

print(prefix, padding, suffix, sep='', end='')
